project:
  type: website

website:
  title: "blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/ResTec-Col
      - icon: twitter
        href: https://x.com/restec_ai
      - icon: facebook
        href: https://www.facebook.com/profile.php?id=61560886237075
      - icon: instagram
        href: https://www.instagram.com/restec.ia/?next=%2F
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css

